### ISSUE TITLE
Redis dequeue does not recover subscription when subscription is lost

### ISSUE THREAD

**Issue by arthursoas** [takenet/elephant#29]
### Description
Redis queue implementation use the Redis subscription concept, to be notified when new itens appears on the queue. In my Understanding it avoids pooling Redis to check for new items. But a problem occurs when the subscription is undone for any reason, like Redis issues, manual intervention, Redis rebooting etc.
Elephant does not check if the subscription is still alive after the first try to subscription, and then it only wait infinitely believing the subscription is there.

### Steps to reproduce
1. Implements a redis queue;
2. Call dequeue method and wait Elephant create a subscription
3. Remove the subscription from your Redis 
4. Wait forever :(

### Usage impact
Your service will starve, awaiting the task resolving.

**Comment by andreminelli** [comment]
Hi @arthursoas . Thanks for your report.

Checking the docs from StackExchange.Redis, it seems that the common operational issues are already handled by [ConnectionMultiplexer](https://stackexchange.github.io/StackExchange.Redis/Basics.html#using-redis-pubsub):

"_Another common use of redis is as a pub/sub message distribution tool; this is also simple, and **in the event of connection failure, the ConnectionMultiplexer will handle all the details of re-subscribing to the requested channels**._"

So in your reprodution you explicitly/manually removed the subscription, right? If so, this seems an edge case - something that probably won't happen on day-to-day usage.

Have you tried other scenarios mentioned by you also (redis rebooting or connection issues)?

**Comment by brenoqueiroz** [comment]
@andreminelli in the @arthursoas sample there is a decorator in ConnectionMultiplexer to reconnect, when this decorator reconnect it create a **new instance** of IConnectionMultiplexer and by default the Elephant class thinks hes already signed.

**Comment by andreminelli** [comment]
So this decorator - a custom code, outside this projeto - is creating a new instance, and should be the responsible for re-do the subscriptions, don't you agree @arthursoas and @brenoqueiroz ?

**Comment by andreminelli** [comment]
Closed after 30 days without responses - and evidences that this issue is on client side.

**Comment by brenoqueiroz** [comment]
@andreminelli at least elephant should be able to allow this state to be reseted so the client dont need to recreate the connection.
