### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [takenet/elephant#9]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by ravpacheco** [comment]
Hi @zuurw, will be a pleasure receive your logo.
Did you think about something in special?

@andrebires take a look in this issue. ;)
Have you thought about some kind of icon for elephant project?

**Comment by andrebires** [comment]
Hi @zuurw, that's very nice! Well, I didn't thought about anything in special, but I like minimalist logos and something in this line would be great. Maybe using only one or two colors and fewer details. But feel free to use your creativity! And thanks for your contribution!

**Comment by zuurw** [comment]
Hi here is my design for your project, see if you like it or not. I can make another one if you want.

![work](https://user-images.githubusercontent.com/40801473/45061830-00d3c500-b09e-11e8-9dbb-cfa7f3e33067.png)

**Comment by ravpacheco** [comment]
Wooow, that is great @zuurw. 🥇 

Thank you very much.

I have just one feedback. 
Do you think is possible make some mark, like a database image, in the object near the elephant?

Any way, congrats for your job.
We can start use the logo right away?

**Comment by zuurw** [comment]
Hi @ravpacheco Im happy that you like it, can you send me a image of the database that you want, and I will try to add to the logo.

What color do you want for the logo? and Typeface If you see I put 2 different typeface, that I think it look good on the logo, so you can choose one.

Best Regards!

**Comment by zuurw** [comment]
Hi I add to the logo a reference to the database, see if you like it.

![proposal](https://user-images.githubusercontent.com/40801473/45153404-c23c2880-b1cb-11e8-8040-bf15e47bb28d.jpg)

**Comment by zuurw** [comment]
Hi did you like the new version of the logo?

**Comment by ravpacheco** [comment]
Hi @zuurw, sorry for delay.

Yes, I saw. 
I liked more the second version (with database reference).

Thank you very much. 🥇 
I will add the logo in home page as soon as possible, ok?

**Comment by ravpacheco** [comment]
I liked the blue one. 
Tks

Regards.

**Comment by zuurw** [comment]
Sorry for the delay in answering, but I had some personal problems to solve and I did not have much time to focus on the projects in github. But now I'm back.
So I will submit PR today!!

**Comment by zuurw** [comment]
Hi @ravpacheco ,
I submit PR with the logo designs, 22 days ago, I dont know if theres is something wrong with the files, or if you dont want the logo design anymore.

Greetings!!!
Zuur
